
name: Build-docker-image-fw

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-18.04

    steps:

    - uses: actions/checkout@v3
    - name: Branch name
      env:
        BRANCH: ${{ github.event.pull_request.head.ref || github.ref_name }}
        GITHUB_REPO: ${{ github.event.pull_request.head.repo.full_name || github.event.repository.name }}
      run: echo running on branch ${BRANCH} on ${GITHUB_REPO} name

    - name: Build the Docker image
      run: docker build --build-arg FW_REPO_URL=https://github.com/${{ github.event.pull_request.head.repo.full_name || github.event.repository.name }}.git --build-arg FW_BRANCH=${{ github.event.pull_request.head.ref || github.head_ref }} . --file Dockerfile --tag fw-bench:$(date +%s)
